// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC00EI6zsKWhS-0Ao3EyD-kX-4Ex54k9Ss',
    appId: '1:109638047146:web:d7cb296e164f6c2ee8c7d3',
    messagingSenderId: '109638047146',
    projectId: 'clase1-a6ce3',
    authDomain: 'clase1-a6ce3.firebaseapp.com',
    storageBucket: 'clase1-a6ce3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGWc11LeSP991l2cPiMwWrrHc9dfOQ2_g',
    appId: '1:109638047146:android:348ff72f8fddf207e8c7d3',
    messagingSenderId: '109638047146',
    projectId: 'clase1-a6ce3',
    storageBucket: 'clase1-a6ce3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw01rAWxglfyswWCH7JqWoU_WFeu8r1iE',
    appId: '1:109638047146:ios:d48ded5987ec0e88e8c7d3',
    messagingSenderId: '109638047146',
    projectId: 'clase1-a6ce3',
    storageBucket: 'clase1-a6ce3.firebasestorage.app',
    iosBundleId: 'com.example.clase1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDw01rAWxglfyswWCH7JqWoU_WFeu8r1iE',
    appId: '1:109638047146:ios:d48ded5987ec0e88e8c7d3',
    messagingSenderId: '109638047146',
    projectId: 'clase1-a6ce3',
    storageBucket: 'clase1-a6ce3.firebasestorage.app',
    iosBundleId: 'com.example.clase1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC00EI6zsKWhS-0Ao3EyD-kX-4Ex54k9Ss',
    appId: '1:109638047146:web:ac4a2fcf44acdfdae8c7d3',
    messagingSenderId: '109638047146',
    projectId: 'clase1-a6ce3',
    authDomain: 'clase1-a6ce3.firebaseapp.com',
    storageBucket: 'clase1-a6ce3.firebasestorage.app',
  );
}
